import type { EngineFinding } from "../ingest";

/** Verdicts recorded by the PurpleGuard validator during the authorized worker run. */
export const RCE_FINDING: EngineFinding = {
  id: "F-2835",
  title: "Unauthenticated code execution via unsafe deserialization in job worker",
  severity: "critical",
  vulnerabilityType: "Remote code execution (unsafe deserialization)",
  repo: "worker-fleet",
  file: "src/jobs/deserializer.ts",
  location: "lines 8-21",
  attackSurface: "Internal queue consumer · amqp://jobs.internal",
  attackPath: [
    "Worker consumes unsigned JSON envelopes from the internal jobs queue",
    "Envelope field `handler` is passed to the Function constructor unvalidated",
    "Validator published a benign marker payload and observed code execution on the worker",
  ],
  explanation:
    "The job worker deserializes queue payloads with the Function constructor, so any producer on the internal network — or any message injected into the queue — executes arbitrary code with worker privileges. The validator executed a harmless probe (creating a file in /tmp) to confirm exploitation without touching production data.",
  remediation:
    "Deserialize to plain data and dispatch through a registry of known handlers. Never construct executable code from queue input.",
  vulnerableCode: [
    "import type { JobEnvelope } from \"../types\";",
    "",
    "export function deserializeJob(raw: string): JobEnvelope {",
    "  const envelope = JSON.parse(raw);",
    "  // Trusted producer required here — but the queue is not producer-authenticated.",
    "  const fn = new Function(\"ctx\", envelope.handler);",
    "  return {",
    "    id: envelope.id,",
    "    run: (ctx: unknown) => fn(ctx),",
    "  };",
    "}",
  ].join("\n"),
  proposedPatch: [
    "import type { JobEnvelope } from \"../types\";",
    'import { HANDLERS } from "./registry";',
    "",
    "export function deserializeJob(raw: string): JobEnvelope {",
    "  const envelope = JSON.parse(raw);",
    "  const name = typeof envelope.handler === \"string\" ? envelope.handler : \"\";",
    "  const fn = HANDLERS[name];",
    "  if (!fn) {",
    "    throw new Error(`Unknown handler: ${name || \"(empty)\"}`);",
    "  }",
    "  return {",
    "    id: envelope.id,",
    "    run: (ctx: unknown) => fn(ctx),",
    "  };",
    "}",
  ].join("\n"),
  fixedCode: [
    "import type { JobEnvelope } from \"../types\";",
    'import { HANDLERS } from "./registry";',
    "",
    "export function deserializeJob(raw: string): JobEnvelope {",
    "  const envelope = JSON.parse(raw);",
    "  const name = typeof envelope.handler === \"string\" ? envelope.handler : \"\";",
    "  const fn = HANDLERS[name];",
    "  if (!fn) {", 
    "    throw new Error(`Unknown handler: ${name || \"(empty)\"}`);",
    "  }",
    "  return {",
    "    id: envelope.id,",
    "    run: (ctx: unknown) => fn(ctx),",
    "  };",
    "}",
  ].join("\n"),
  reTestChecks: [
    "Marker payload no longer executes on the worker",
    "Unknown handler names are rejected at deserialization",
    "Registered handlers keep working for legitimate jobs",
  ],
  vulnerableMarker: "new Function(",
  evidence: [
    {
      id: "F-2835-ev-1",
      kind: "log",
      label: "Worker log — probe executed",
      content: [
        "[worker-7] job received id=probe-1 handler=(inline)",
        "[worker-7] executing handler payload",
        "[worker-7] marker file created: /tmp/.pg_probe_1701 (RCE CONFIRMED)",
        "[validator] benign probe: write to /tmp only, no production data touched",
      ].join("\n"),
    },
    {
      id: "F-2835-ev-2",
      kind: "code",
      label: "Unsafe deserialization site",
      content: [
        "deserializer.ts:8",
        "  const fn = new Function(\"ctx\", envelope.handler);",
        "",
        "Call path: queue consumer -> deserializeJob -> new Function -> arbitrary code",
      ].join("\n"),
    },
    {
      id: "F-2835-ev-3",
      kind: "http",
      label: "Queue message used for the probe",
      content: [
        "PUBLISH jobs.internal",
        "",
        '{ "id": "probe-1", "handler": "require(\'fs\').writeFileSync(\'/tmp/.pg_probe_1701\', \'ok\')" }',
      ].join("\n"),
    },
  ],
  testerNote:
    "Authorized probe executed a harmless file creation in /tmp on an isolated worker. No persistence, no lateral movement, no data access.",
  attackSteps: [
    {
      name: "Marker payload execution",
      description: "Publish the probe envelope and check for execution on the worker",
      criteria: "No marker file appears in the worker sandbox after the probe message",
      verdict: "exploitable",
      log: [
        "[validator] probe message published to jobs.internal",
        "[worker-7] executing handler payload",
        "[worker-7] marker file created: /tmp/.pg_probe_1701 (RCE CONFIRMED)",
      ],
    },
    {
      name: "Handler allowlist enforcement",
      description: "Send an envelope with an unregistered handler name",
      criteria: "Unknown handlers are rejected before any code runs",
      verdict: "exploitable",
      log: [
        "[validator] unknown handler 'pg-probe' accepted",
        "[validator] constructor invoked with attacker-controlled body",
      ],
    },
    {
      name: "Registry dispatch for legitimate jobs",
      description: "Confirm registered handlers still run after a fix",
      criteria: "Legitimate job completes successfully",
      verdict: "exploitable",
      log: ["[validator] legitimate job 'render-invoice' queued"],
    },
  ],
  runId: "run-2026-09-24-worker-fleet-rce-01",
  startedAt: "2026-09-24T08:41:37Z",
};
