#!/usr/bin/env bash
# fix-convex-types.sh — Phase 3 green gate. Idempotent: safe to re-run.
set -uo pipefail
cd "$(dirname "$0")/.."

fail() { echo; echo "FAIL: $1"; echo "-> Paste this script's full output back."; exit 1; }

echo "== 0/5  Preflight =="
command -v npx >/dev/null || fail "npx not found (node missing or PATH broken)"
NODE_MAJOR=$(node -p 'process.versions.node.split(".")[0]')
[ "$NODE_MAJOR" -ge 20 ] || fail "node >= 20 required, found $NODE_MAJOR"
[ -f convex.json ] || fail "convex.json missing at repo root"
grep -q '"functions": "src/convex"' convex.json || fail 'convex.json does not point functions at src/convex'
[ -f src/convex/schema.ts ] || fail "src/convex/schema.ts missing"
echo "ok"

echo "== 1/5  Remove Vly dev-preview artifacts =="
if [ -f vly-toolbar-readonly.tsx ]; then rm -f vly-toolbar-readonly.tsx; echo "removed"; else echo "already absent"; fi

echo "== 2/5  Wipe ALL stale Convex generated types =="
rm -rf src/convex/_generated
rm -rf node_modules/.tmp
echo "wiped _generated + tsbuildinfo cache"

echo "== 3/5  Regenerate Convex types =="
npx convex dev --once 2>&1 | tail -3 || fail "convex dev --once failed (auth or deployment)"
ls src/convex/_generated || fail "_generated still missing after codegen"
for f in api.d.ts api.js server.d.ts server.js; do
  [ -s "src/convex/_generated/$f" ] || fail "_generated/$f missing or empty"
done
grep -q "workflow" src/convex/_generated/api.d.ts || fail "api.d.ts lacks workflow module - codegen wrote a stub"
echo "types verified: real, non-stub, all modules present"

echo "== 4/5  TypeScript build (strict, noEmit) =="
npx tsc -b --noEmit || fail "tsc errors above - DO NOT patch _generated by hand; re-run this script"
echo "tsc: 0 errors"

echo "== 5/5  Production build =="
npx vite build || fail "vite build failed"
echo
echo "ALL GREEN - tsc 0 errors, vite build ok."
echo "Now run:  python -m pytest tests/ -q   and paste both outputs."
