"""ECC extraction integrity + integration-boundary tests.

These guard the vendored `ecc/` subtree: that it is present, attributed to the
pinned ECC revision, checksum-intact, free of secrets/build artifacts, and that
PurpleGuard does not yet import ECC internals directly (the controlled
`ecc/bridge/` is the only permitted future surface).
"""

import hashlib
import json
import re
import unittest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
ECC = PROJECT_ROOT / "ecc"

PINNED_COMMIT = "9c19aabe0f6506a4d0f47945e3f6cae59d7e4e7c"

EXPECTED_PATHS = [
    "README.md",
    "PROVENANCE.md",
    "AGENTS.md",
    "MANIFEST.json",
    "CHECKSUMS.sha256",
    "LICENSE",
    "ecc2.toml",
    "agent.yaml",
    "bridge/README.md",
    "ecc2/Cargo.toml",
    "ecc2/src/main.rs",
    "ecc2/src/session/manager.rs",
    "integrations/aura/adapter.py",
    "integrations/aura/tests/test_adapter.py",
    "schemas/state-store.schema.json",
    "docs/ECC-AGENTS.md",
    "research/ecc2-codebase-analysis.md",
    "bridge/contracts.py",
    "bridge/client.py",
]

FORBIDDEN_DIRS = {"node_modules", "target", ".git", "venv", ".venv", ".tox"}

# Runtime-generated by our own bridge package; not part of the vendored snapshot.
GENERATED_DIRS = {"__pycache__", ".pytest_cache"}

SECRET_PATTERNS = [
    re.compile(r"sk-[A-Za-z0-9]{20,}"),
    re.compile(r"AKIA[0-9A-Z]{16}"),
    re.compile(r"ghp_[A-Za-z0-9]{20,}"),
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"),
]

TEXT_SUFFIXES = {".md", ".json", ".toml", ".yaml", ".yml", ".py", ".rs", ".sh", ".txt", ".lock"}


def _iter_ecc_files():
    files = []
    for path in ECC.rglob("*"):
        if not path.is_file():
            continue
        if any(part in GENERATED_DIRS for part in path.parts):
            continue
        files.append(path)
    return files


class EccExtractionTreeTests(unittest.TestCase):

    def test_expected_paths_exist(self):
        missing = [rel for rel in EXPECTED_PATHS if not (ECC / rel).is_file()]
        self.assertEqual(missing, [], f"missing extracted ECC paths: {missing}")

    def test_curated_counts(self):
        # Enough to be useful, small enough to stay curated (not the 3,265-file ECC).
        self.assertEqual(len(list((ECC / "agents").glob("*.md"))), 20)
        self.assertEqual(len(list((ECC / "commands").glob("*.md"))), 41)
        self.assertEqual(len(list((ECC / "rules").rglob("*.md"))), 24)
        self.assertEqual(len(list((ECC / "schemas").glob("*.json"))), 10)
        self.assertEqual(
            len(list((ECC / "skills").glob("*/SKILL.md"))), 16
        )

    def test_provenance_is_pinned(self):
        provenance = (ECC / "PROVENANCE.md").read_text()
        self.assertIn(PINNED_COMMIT, provenance)
        self.assertIn("learnkit-tech/ECC", provenance)
        self.assertIn("MIT", provenance)
        # The harness config that wires ECC -> PurpleGuard must be present and intact.
        harness = (ECC / "ecc2.toml").read_text()
        self.assertIn("harness_runners.purpleguard", harness)
        self.assertIn("purpleguard_runner.py", harness)


class EccManifestTests(unittest.TestCase):

    def setUp(self):
        self.manifest = json.loads((ECC / "MANIFEST.json").read_text())

    def test_manifest_shape(self):
        self.assertEqual(self.manifest["kind"], "ecc-extraction-manifest")
        source = self.manifest["source"]
        self.assertEqual(source["commit"], PINNED_COMMIT)
        self.assertFalse(source["upstream_modified"])
        self.assertTrue(self.manifest["extraction"]["tracked_files_only"])

    def test_every_component_has_provenance_and_disposition(self):
        components = self.manifest["components"]
        self.assertGreater(len(components), 0)
        for component in components:
            with self.subTest(component=component.get("id")):
                for key in ("id", "source_paths", "destination", "disposition", "reason"):
                    self.assertIn(key, component)
                self.assertTrue(component["source_paths"])
                self.assertTrue(component["destination"])

    def test_decision_a_defers_src_llm(self):
        decisions = self.manifest["decisions"]
        self.assertIn("retain PurpleGuard", decisions["llm_provider_layer"]["decision"])
        deferred = {item["source_paths"][0] for item in self.manifest["deferred"]}
        self.assertIn("src/llm/", deferred)
        # It must not have been extracted.
        self.assertFalse((ECC / "src" / "llm").exists())

    def test_agent_reach_is_marked_blocked_not_fabricated(self):
        blocked = {item["item"] for item in self.manifest["blocked"]}
        self.assertIn("Agent-Reach", blocked)
        self.assertFalse((ECC / "Agent-Reach").exists())


class EccIntegrityTests(unittest.TestCase):

    def test_checksums_cover_every_file_and_match(self):
        checksum_file = ECC / "CHECKSUMS.sha256"
        self.assertTrue(checksum_file.is_file())

        listed = {}
        for line in checksum_file.read_text().splitlines():
            if not line.strip():
                continue
            digest, rel = line.split(None, 1)
            rel = rel.strip()
            if rel.startswith("./"):
                rel = rel[2:]
            listed[rel] = digest

        on_disk = {
            str(p.relative_to(ECC))
            for p in _iter_ecc_files()
            if p.name != "CHECKSUMS.sha256"
        }

        self.assertEqual(
            sorted(on_disk), sorted(listed),
            "CHECKSUMS.sha256 must list exactly the extracted files",
        )

        for rel, expected in listed.items():
            with self.subTest(file=rel):
                actual = hashlib.sha256((ECC / rel).read_bytes()).hexdigest()
                self.assertEqual(actual, expected, f"checksum drift: {rel}")

    def test_no_secrets_or_forbidden_artifacts(self):
        for directory in ECC.rglob("*"):
            if directory.is_dir():
                if directory.name in GENERATED_DIRS:
                    continue
                self.assertNotIn(
                    directory.name, FORBIDDEN_DIRS,
                    f"forbidden artifact dir: {directory}",
                )

        for path in _iter_ecc_files():
            if path.suffix.lower() not in TEXT_SUFFIXES:
                continue
            text = path.read_text(errors="ignore")
            for pattern in SECRET_PATTERNS:
                self.assertIsNone(
                    pattern.search(text),
                    f"secret-like value in {path.relative_to(ECC)}",
                )

    def test_purpleguard_does_not_import_ecc_directly(self):
        """Only `ecc/bridge/` may import ECC. Until the bridge exists, no
        PurpleGuard module may import from the vendored `ecc/` namespace."""
        import_pattern = re.compile(r"^\s*(from\s+ecc(\.|\s)|import\s+ecc(\.|\s|$))", re.M)
        offenders = []
        for path in PROJECT_ROOT.rglob("*.py"):
            rel = path.relative_to(PROJECT_ROOT)
            if rel.parts[0] in {"ecc", "tests", "build"}:
                continue
            if import_pattern.search(path.read_text(errors="ignore")):
                offenders.append(str(rel))
        self.assertEqual(offenders, [], f"direct ecc imports outside bridge: {offenders}")


if __name__ == "__main__":
    unittest.main()
